Install GHC and Cabal via GHCUp

diff --git a/haskell/Dockerfile b/haskell/Dockerfile
--- a/haskell/Dockerfile
+++ b/haskell/Dockerfile
@@ -1,18 +1,17 @@
 FROM ubuntu:jammy
 
-# Install packages
-RUN apt-get update && apt-get install -y \
-      software-properties-common \
-      bash \
-      libtinfo5 \
-    --no-install-recommends \
- && rm -r /var/lib/apt/lists/*
-
 # Switch to bash
 SHELL ["/bin/bash", "-c"]
 
-# Add GHC to the path
-ENV PATH="/opt/ghc/bin:${PATH}"
+# Install packages
+RUN apt-get update && apt-get install -y \
+      build-essential \
+      curl \
+      ca-certificates \
+      libffi-dev libffi8ubuntu1 libgmp-dev libgmp10 libncurses-dev libncurses5 \
+      libtinfo5 \
+    --no-install-recommends \
+ && rm -r /var/lib/apt/lists/*
 
 # Create student user
 ARG GNAME=student
@@ -20,32 +19,39 @@ ARG GID=1000
 ARG UNAME=student
 ARG UID=1000
 ARG UHOME=/user_code
-RUN set -o errexit -o nounset \
- && addgroup --gid ${GID} "${GNAME}" \
- && adduser --home "${UHOME}" --disabled-password --uid ${UID} --ingroup "${GNAME}" "${UNAME}"
+RUN set -o errexit -o nounset
+RUN addgroup --gid ${GID} "${GNAME}"
+RUN adduser --home "${UHOME}" --disabled-password --uid ${UID} --ingroup "${GNAME}" "${UNAME}" --gecos ""
 
-# Install libraries and test runner
-# Do this in one go to avoid creation of large intermediate images
-# that contain the whole Cabal index
+# Switch to student user
 WORKDIR ${UHOME}
 ENV HOME ${UHOME}
+USER ${UNAME}
+
+# Install GHC, Cabal and HLS via GHCUP
+# any nonzero value for noninteractive installation
+ENV BOOTSTRAP_HASKELL_NONINTERACTIVE=1
+# any nonzero value to only install ghcup itself
+ENV BOOTSTRAP_HASKELL_MINIMAL=1
+# download and installation of ghcup
+RUN curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
+# Add ghcup directory to the path
+ENV PATH="${UHOME}/.ghcup/bin:${PATH}"
+# install ghc, cabal, and hls
+RUN ghcup install ghc 9.0.2 --set
+RUN ghcup install cabal 3.6.2.0
+
+# Install libraries and test runner
 COPY --chown=${UNAME} testrunner/ ${UHOME}
-RUN add-apt-repository ppa:hvr/ghc \
- && apt-get update && apt-get install -y \
-      ghc-9.0.1 \
-      cabal-install-3.4 \
-    --no-install-recommends \
- && rm -r /var/lib/apt/lists/* \
- && cabal new-update \
+RUN cabal update \
  && cabal v2-install --enable-executable-dynamic --lib QuickCheck xml \
  && cabal v2-install --enable-executable-dynamic \
- && rm ~/.cabal/packages/hackage.haskell.org/*-index.* \
- && rm -r /opt/ghc/*/lib/ghc-*/Cabal-* \
- && find ~/.cabal -type f -name '*.a' -exec rm {} + \
- && find /opt/ghc -type f -name '*.a' -exec rm {} + \
- && find /opt/ghc -type f -name '*.hi' -exec rm {} + \
- && find /opt/ghc -name '*-prof' -exec rm -r {} + \
- && chown -R ${UNAME}:${GNAME} ${UHOME}/.cabal/
+ && rm ${UHOME}/.cabal/packages/hackage.haskell.org/*-index.* \
+ && rm -r ${UHOME}/.ghcup/ghc/*/lib/ghc-*/Cabal-* \
+ && find ${UHOME}/.cabal -type f -name '*.a' -exec rm {} + \
+ && find ${UHOME}/.ghcup/ghc -type f -name '*.a' -exec rm {} + \
+ && find ${UHOME}/.ghcup/ghc -type f -name '*.hi' -exec rm {} + \
+ && find ${UHOME}/.ghcup/ghc -name '*-prof' -exec rm -r {} +
 
 # Copy user code
 COPY --chown=${UNAME} user_code/ ${UHOME}
@@ -54,7 +60,6 @@ COPY --chown=${UNAME} user_code/ ${UHOME}
 RUN chmod u-w truncate_output.sh
 
 # Run
-USER ${UNAME}
 RUN mkdir ${UHOME}/output
 CMD ( ~/.cabal/bin/TestRunner | tee output/stdout.txt ) 3>&1 1>&2 2>&3 | tee output/stderr.txt \
  && ./truncate_output.sh
